import type { ColumnConfig } from "@/types/stock"
import { getColumnDisplayName } from "./columnNames"

export const COLUMNS: ColumnConfig[] = [
  {
    key: "symbol",
    displayName: getColumnDisplayName("symbol"),
    filterName: "Symbol",
    type: "string",
    group: "General",
  },
  {
    key: "total_weeks",
    displayName: getColumnDisplayName("total_weeks"),
    filterName: "Weeks",
    type: "number",
    decimals: 0,
    group: "General",
  },
  // Returns
  {
    key: "change_pct_1w",
    displayName: getColumnDisplayName("change_pct_1w"),
    filterName: "1W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_pct_2w",
    displayName: getColumnDisplayName("change_pct_2w"),
    filterName: "2W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_pct_4w",
    displayName: getColumnDisplayName("change_pct_4w"),
    filterName: "4W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_pct_13w",
    displayName: getColumnDisplayName("change_pct_13w"),
    filterName: "13W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_pct_26w",
    displayName: getColumnDisplayName("change_pct_26w"),
    filterName: "26W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_pct_52w",
    displayName: getColumnDisplayName("change_pct_52w"),
    filterName: "52W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  // Trend — linear regression
  {
    key: "slope_pct_4w",
    displayName: getColumnDisplayName("slope_pct_4w"),
    filterName: "Slope 4W",
    type: "number",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "slope_pct_13w",
    displayName: getColumnDisplayName("slope_pct_13w"),
    filterName: "Slope 13W",
    type: "number",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "slope_pct_26w",
    displayName: getColumnDisplayName("slope_pct_26w"),
    filterName: "Slope 26W",
    type: "number",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "slope_pct_52w",
    displayName: getColumnDisplayName("slope_pct_52w"),
    filterName: "Slope 52W",
    type: "number",
    decimals: 2,
    group: "Trend",
  },
  {
    key: "r_squared_4w",
    displayName: getColumnDisplayName("r_squared_4w"),
    filterName: "R² 4W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "r_squared_13w",
    displayName: getColumnDisplayName("r_squared_13w"),
    filterName: "R² 13W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "r_squared_26w",
    displayName: getColumnDisplayName("r_squared_26w"),
    filterName: "R² 26W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "r_squared_52w",
    displayName: getColumnDisplayName("r_squared_52w"),
    filterName: "R² 52W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  // Trend — log regression
  {
    key: "log_slope_13w",
    displayName: getColumnDisplayName("log_slope_13w"),
    filterName: "Log Slope 13W",
    type: "number",
    decimals: 4,
    group: "Trend",
  },
  {
    key: "log_r_squared_13w",
    displayName: getColumnDisplayName("log_r_squared_13w"),
    filterName: "Log R² 13W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "log_slope_26w",
    displayName: getColumnDisplayName("log_slope_26w"),
    filterName: "Log Slope 26W",
    type: "number",
    decimals: 4,
    group: "Trend",
  },
  {
    key: "log_r_squared_26w",
    displayName: getColumnDisplayName("log_r_squared_26w"),
    filterName: "Log R² 26W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "log_slope_52w",
    displayName: getColumnDisplayName("log_slope_52w"),
    filterName: "Log Slope 52W",
    type: "number",
    decimals: 4,
    group: "Trend",
  },
  {
    key: "log_r_squared_52w",
    displayName: getColumnDisplayName("log_r_squared_52w"),
    filterName: "Log R² 52W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  // Volatility (swings)
  {
    key: "max_jump_pct_1w",
    displayName: getColumnDisplayName("max_jump_pct_1w"),
    filterName: "Max 1W Jump",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_drop_pct_1w",
    displayName: getColumnDisplayName("max_drop_pct_1w"),
    filterName: "Max 1W Drop",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_jump_pct_2w",
    displayName: getColumnDisplayName("max_jump_pct_2w"),
    filterName: "Max 2W Jump",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_drop_pct_2w",
    displayName: getColumnDisplayName("max_drop_pct_2w"),
    filterName: "Max 2W Drop",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_jump_pct_4w",
    displayName: getColumnDisplayName("max_jump_pct_4w"),
    filterName: "Max 4W Jump",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_drop_pct_4w",
    displayName: getColumnDisplayName("max_drop_pct_4w"),
    filterName: "Max 4W Drop",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  // Volatility (statistical)
  {
    key: "return_std_52w",
    displayName: getColumnDisplayName("return_std_52w"),
    filterName: "Weekly Return Std",
    type: "number",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "downside_std_52w",
    displayName: getColumnDisplayName("downside_std_52w"),
    filterName: "Downside Std",
    type: "number",
    decimals: 2,
    group: "Volatility",
  },
  // Stability — drawdown
  {
    key: "max_drawdown_pct_4w",
    displayName: getColumnDisplayName("max_drawdown_pct_4w"),
    filterName: "Drawdown 4W",
    type: "percent",
    decimals: 2,
    group: "Stability",
  },
  {
    key: "max_drawdown_pct_13w",
    displayName: getColumnDisplayName("max_drawdown_pct_13w"),
    filterName: "Drawdown 13W",
    type: "percent",
    decimals: 2,
    group: "Stability",
  },
  {
    key: "max_drawdown_pct_26w",
    displayName: getColumnDisplayName("max_drawdown_pct_26w"),
    filterName: "Drawdown 26W",
    type: "percent",
    decimals: 2,
    group: "Stability",
  },
  {
    key: "max_drawdown_pct_52w",
    displayName: getColumnDisplayName("max_drawdown_pct_52w"),
    filterName: "Max Drawdown",
    type: "percent",
    decimals: 2,
    group: "Stability",
  },
  // Stability — % up-weeks
  {
    key: "pct_weeks_positive_4w",
    displayName: getColumnDisplayName("pct_weeks_positive_4w"),
    filterName: "% Weeks + 4W",
    type: "number",
    decimals: 2,
    group: "Stability",
  },
  {
    key: "pct_weeks_positive_13w",
    displayName: getColumnDisplayName("pct_weeks_positive_13w"),
    filterName: "% Weeks + 13W",
    type: "number",
    decimals: 2,
    group: "Stability",
  },
  {
    key: "pct_weeks_positive_26w",
    displayName: getColumnDisplayName("pct_weeks_positive_26w"),
    filterName: "% Weeks + 26W",
    type: "number",
    decimals: 2,
    group: "Stability",
  },
  {
    key: "pct_weeks_positive_52w",
    displayName: getColumnDisplayName("pct_weeks_positive_52w"),
    filterName: "% Weeks Positive",
    type: "number",
    decimals: 2,
    group: "Stability",
  },
  // Momentum shape
  {
    key: "acceleration_pct_4w",
    displayName: getColumnDisplayName("acceleration_pct_4w"),
    filterName: "Acceleration 4W",
    type: "number",
    decimals: 3,
    group: "Momentum",
  },
  {
    key: "acceleration_pct_13w",
    displayName: getColumnDisplayName("acceleration_pct_13w"),
    filterName: "Acceleration 13W",
    type: "number",
    decimals: 3,
    group: "Momentum",
  },
  {
    key: "acceleration_pct_26w",
    displayName: getColumnDisplayName("acceleration_pct_26w"),
    filterName: "Acceleration 26W",
    type: "number",
    decimals: 3,
    group: "Momentum",
  },
  {
    key: "acceleration_pct_52w",
    displayName: getColumnDisplayName("acceleration_pct_52w"),
    filterName: "Acceleration 52W",
    type: "number",
    decimals: 3,
    group: "Momentum",
  },
  {
    key: "from_high_pct_4w",
    displayName: getColumnDisplayName("from_high_pct_4w"),
    filterName: "From 4W High",
    type: "percent",
    decimals: 2,
    group: "Momentum",
  },
  // Moving average structure
  {
    key: "price_vs_ma20_pct",
    displayName: getColumnDisplayName("price_vs_ma20_pct"),
    filterName: "Price vs MA20",
    type: "percent",
    decimals: 2,
    group: "Moving Average",
  },
  {
    key: "price_vs_ma50_pct",
    displayName: getColumnDisplayName("price_vs_ma50_pct"),
    filterName: "Price vs MA50",
    type: "percent",
    decimals: 2,
    group: "Moving Average",
  },
  {
    key: "price_vs_ma100_pct",
    displayName: getColumnDisplayName("price_vs_ma100_pct"),
    filterName: "Price vs MA100",
    type: "percent",
    decimals: 2,
    group: "Moving Average",
  },
  {
    key: "price_vs_ma200_pct",
    displayName: getColumnDisplayName("price_vs_ma200_pct"),
    filterName: "Price vs MA200",
    type: "percent",
    decimals: 2,
    group: "Moving Average",
  },
  {
    key: "ma50_vs_ma200_pct",
    displayName: getColumnDisplayName("ma50_vs_ma200_pct"),
    filterName: "MA50 vs MA200",
    type: "percent",
    decimals: 2,
    group: "Moving Average",
  },
]

/** Column keys shown by default — the most important 8 for quick screening */
export const DEFAULT_VISIBLE_COLUMNS: Set<string> = new Set([
  "symbol",
  "change_pct_13w",
  "change_pct_26w",
  "change_pct_52w",
  "r_squared_52w",
  "return_std_52w",
  "max_drawdown_pct_52w",
  "from_high_pct_4w",
])
