import type { ColumnConfig } from "@/types/stock"
import { getColumnDisplayName } from "./columnNames"

export const COLUMNS: ColumnConfig[] = [
  {
    key: "symbol",
    displayName: getColumnDisplayName("symbol"),
    filterName: "Symbol",
    type: "string",
    group: "General",
  },
  {
    key: "total_weeks",
    displayName: getColumnDisplayName("total_weeks"),
    filterName: "Weeks",
    type: "number",
    decimals: 0,
    group: "General",
  },
  // Return metrics
  {
    key: "change_1w_pct",
    displayName: getColumnDisplayName("change_1w_pct"),
    filterName: "1W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_2w_pct",
    displayName: getColumnDisplayName("change_2w_pct"),
    filterName: "2W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_4w_pct",
    displayName: getColumnDisplayName("change_4w_pct"),
    filterName: "4W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_13w_pct",
    displayName: getColumnDisplayName("change_13w_pct"),
    filterName: "13W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_26w_pct",
    displayName: getColumnDisplayName("change_26w_pct"),
    filterName: "26W Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  {
    key: "change_1y_pct",
    displayName: getColumnDisplayName("change_1y_pct"),
    filterName: "1Y Change",
    type: "percent",
    decimals: 2,
    group: "Returns",
  },
  // Trend metrics
  {
    key: "linear_slope_pct",
    displayName: getColumnDisplayName("linear_slope_pct"),
    filterName: "Linear Slope/Week",
    type: "number",
    decimals: 2,
    group: "Trend",
  },
  {
    key: "linear_r_squared",
    displayName: getColumnDisplayName("linear_r_squared"),
    filterName: "Linear R²",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "log_slope",
    displayName: getColumnDisplayName("log_slope"),
    filterName: "Slope/Year",
    type: "number",
    decimals: 4,
    group: "Trend",
  },
  {
    key: "log_r_squared",
    displayName: getColumnDisplayName("log_r_squared"),
    filterName: "Log R²",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "slope_13w_pct",
    displayName: getColumnDisplayName("slope_13w_pct"),
    filterName: "Slope 13W",
    type: "number",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "r_squared_13w",
    displayName: getColumnDisplayName("r_squared_13w"),
    filterName: "R² 13W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "r_squared_4w",
    displayName: getColumnDisplayName("r_squared_4w"),
    filterName: "R² 4W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "slope_26w_pct",
    displayName: getColumnDisplayName("slope_26w_pct"),
    filterName: "Slope 26W",
    type: "number",
    decimals: 3,
    group: "Trend",
  },
  {
    key: "r_squared_26w",
    displayName: getColumnDisplayName("r_squared_26w"),
    filterName: "R² 26W",
    type: "r_squared",
    decimals: 3,
    group: "Trend",
  },
  // Volatility (swings)
  {
    key: "max_jump_1w_pct",
    displayName: getColumnDisplayName("max_jump_1w_pct"),
    filterName: "Max 1W Jump",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_drop_1w_pct",
    displayName: getColumnDisplayName("max_drop_1w_pct"),
    filterName: "Max 1W Drop",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_jump_2w_pct",
    displayName: getColumnDisplayName("max_jump_2w_pct"),
    filterName: "Max 2W Jump",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_drop_2w_pct",
    displayName: getColumnDisplayName("max_drop_2w_pct"),
    filterName: "Max 2W Drop",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_jump_4w_pct",
    displayName: getColumnDisplayName("max_jump_4w_pct"),
    filterName: "Max 4W Jump",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "max_drop_4w_pct",
    displayName: getColumnDisplayName("max_drop_4w_pct"),
    filterName: "Max 4W Drop",
    type: "percent",
    decimals: 2,
    group: "Volatility",
  },
  // Volatility (statistical)
  {
    key: "weekly_return_std",
    displayName: getColumnDisplayName("weekly_return_std"),
    filterName: "Weekly Return Std",
    type: "number",
    decimals: 2,
    group: "Volatility",
  },
  {
    key: "downside_std",
    displayName: getColumnDisplayName("downside_std"),
    filterName: "Downside Std",
    type: "number",
    decimals: 2,
    group: "Volatility",
  },
  // Stability
  {
    key: "max_drawdown_pct",
    displayName: getColumnDisplayName("max_drawdown_pct"),
    filterName: "Max Drawdown",
    type: "percent",
    decimals: 2,
    group: "Stability",
  },
  {
    key: "pct_weeks_positive",
    displayName: getColumnDisplayName("pct_weeks_positive"),
    filterName: "% Weeks Positive",
    type: "number",
    decimals: 2,
    group: "Stability",
  },
  // Momentum shape
  {
    key: "acceleration_13w",
    displayName: getColumnDisplayName("acceleration_13w"),
    filterName: "Acceleration 13W",
    type: "number",
    decimals: 3,
    group: "Momentum",
  },
  {
    key: "pct_from_4w_high",
    displayName: getColumnDisplayName("pct_from_4w_high"),
    filterName: "From 4W High",
    type: "percent",
    decimals: 2,
    group: "Momentum",
  },
]

/** Column keys shown by default — the most important 8 for quick screening */
export const DEFAULT_VISIBLE_COLUMNS: Set<string> = new Set([
  "symbol",
  "change_13w_pct",
  "change_26w_pct",
  "change_1y_pct",
  "linear_r_squared",
  "weekly_return_std",
  "max_drawdown_pct",
  "pct_from_4w_high",
])
