import type { ColumnConfig } from "@/types/stock"
import { getColumnDisplayName } from "./columnNames"

export const COLUMNS: ColumnConfig[] = [
  {
    key: "symbol",
    displayName: getColumnDisplayName("symbol"),
    filterName: "Symbol",
    type: "string",
  },
  {
    key: "total_weeks",
    displayName: getColumnDisplayName("total_weeks"),
    filterName: "Weeks",
    type: "number",
    decimals: 0,
  },
  {
    key: "max_jump_1w_pct",
    displayName: getColumnDisplayName("max_jump_1w_pct"),
    filterName: "Max 1W Jump",
    type: "percent",
    decimals: 2,
  },
  {
    key: "max_drop_1w_pct",
    displayName: getColumnDisplayName("max_drop_1w_pct"),
    filterName: "Max 1W Drop",
    type: "percent",
    decimals: 2,
  },
  {
    key: "max_jump_2w_pct",
    displayName: getColumnDisplayName("max_jump_2w_pct"),
    filterName: "Max 2W Jump",
    type: "percent",
    decimals: 2,
  },
  {
    key: "max_drop_2w_pct",
    displayName: getColumnDisplayName("max_drop_2w_pct"),
    filterName: "Max 2W Drop",
    type: "percent",
    decimals: 2,
  },
  {
    key: "max_jump_4w_pct",
    displayName: getColumnDisplayName("max_jump_4w_pct"),
    filterName: "Max 4W Jump",
    type: "percent",
    decimals: 2,
  },
  {
    key: "max_drop_4w_pct",
    displayName: getColumnDisplayName("max_drop_4w_pct"),
    filterName: "Max 4W Drop",
    type: "percent",
    decimals: 2,
  },
  // {
  //   key: "trend_slope_pct",
  //   displayName: "Slope/Wk",
  //   filterName: "Slope/Week",
  //   type: "percent",
  //   decimals: 3,
  // },
  {
    key: "linear_slope_pct",
    displayName: getColumnDisplayName("linear_slope_pct"),
    filterName: "Linear Slope/Week",
    type: "number",
    decimals: 2,
  },
  {
    key: "linear_r_squared",
    displayName: getColumnDisplayName("linear_r_squared"),
    filterName: "Linear R²",
    type: "r_squared",
    decimals: 3,
  },
  {
    key: "log_slope",
    displayName: getColumnDisplayName("log_slope"),
    filterName: "Slope/Year",
    type: "number",
    decimals: 4,
  },
  {
    key: "log_r_squared",
    displayName: getColumnDisplayName("log_r_squared"),
    filterName: "Log R²",
    type: "r_squared",
    decimals: 3,
  },
  {
    key: "change_1w_pct",
    displayName: getColumnDisplayName("change_1w_pct"),
    filterName: "1W Change",
    type: "percent",
    decimals: 2,
  },
  {
    key: "change_2w_pct",
    displayName: getColumnDisplayName("change_2w_pct"),
    filterName: "2W Change",
    type: "percent",
    decimals: 2,
  },
  {
    key: "change_1m_pct",
    displayName: getColumnDisplayName("change_1m_pct"),
    filterName: "1M Change",
    type: "percent",
    decimals: 2,
  },
  {
    key: "change_3m_pct",
    displayName: getColumnDisplayName("change_3m_pct"),
    filterName: "3M Change",
    type: "percent",
    decimals: 2,
  },
  {
    key: "change_6m_pct",
    displayName: getColumnDisplayName("change_6m_pct"),
    filterName: "6M Change",
    type: "percent",
    decimals: 2,
  },
  {
    key: "change_1y_pct",
    displayName: getColumnDisplayName("change_1y_pct"),
    filterName: "1Y Change",
    type: "percent",
    decimals: 2,
  },
]
